apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:            
      containers:
      - name: api
        image: leonardosistemas/desafio-sword:latest
        ports:
        - containerPort: 9075
        imagePullPolicy: Always